<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hypertextmodel"
    nsURI="http://hypertextmodel/1.0" nsPrefix="hypertextmodel">
  <eClassifiers xsi:type="ecore:EClass" name="WebPage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" upperBound="-1" eType="#//LinkKat2"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkJoinNode" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" upperBound="-1" eType="#//LinkKat1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HypertextModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LinkJoinNodes" upperBound="-1"
        eType="#//LinkJoinNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="WebPages" upperBound="-1"
        eType="#//WebPage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="staticPage" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="homepage" lowerBound="1"
        eType="#//staticPage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Content" upperBound="-1"
        eType="#//staticContent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="dynamicPage" abstract="true" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="staticContent" instanceTypeName="staticContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityPages" eSuperTypes="#//dynamicPage">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="EntityPages"/>
    </eAnnotations>
    <eOperations name="showInstanz" lowerBound="1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InnerPage" upperBound="-1"
        eType="#//dynamicPage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexPages" eSuperTypes="#//dynamicPage">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="IndexPages"/>
    </eAnnotations>
    <eOperations name="showAll" lowerBound="1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IndexPage" upperBound="-1"
        eType="#//IndexPages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamicContent" lowerBound="1"
        upperBound="-1" eType="#//DynContent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdatePage" eSuperTypes="#//EntityPages">
    <eOperations name="editEntity" lowerBound="1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" lowerBound="1" eType="#//OK"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" lowerBound="1" eType="#//KO"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeletePage" eSuperTypes="#//EntityPages">
    <eOperations name="deleteEntity" lowerBound="1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OKLink" lowerBound="1"
        eType="#//OK" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" lowerBound="1" eType="#//KO"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreatePage" eSuperTypes="#//EntityPages">
    <eOperations name="createEntity" lowerBound="1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" lowerBound="1" eType="#//OK"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" lowerBound="1" eType="#//KO"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Links" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" lowerBound="1" eType="#//LinkParamater"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetPage" lowerBound="1"
        eType="#//WebPage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonContextualLinks" eSuperTypes="#//LinkKat2"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContextualLinks" eSuperTypes="#//LinkKat2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Entity" lowerBound="1"
        upperBound="-1" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OK" eSuperTypes="#//LinkKat1"/>
  <eClassifiers xsi:type="ecore:EClass" name="KO" eSuperTypes="#//LinkKat1"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkParamater">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DynContent" instanceTypeName="javaObjekt"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkKat1" abstract="true" eSuperTypes="#//Links"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkKat2" abstract="true" eSuperTypes="#//Links"/>
</ecore:EPackage>
