<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hypertextmodel"
    nsURI="http://hypertextmodel/1.0" nsPrefix="hypertextmodel">
  <eClassifiers xsi:type="ecore:EClass" name="WebPage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkJoinNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="HypertextModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LinkJoinNodes" upperBound="-1"
        eType="#//LinkJoinNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="WebPages" upperBound="-1"
        eType="#//WebPage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="staticPage" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="homepage" lowerBound="1"
        eType="#//staticPage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Content" upperBound="-1"
        eType="#//staticContent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="dynamicPage" abstract="true" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="staticContent" instanceTypeName="staticContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityPages" eSuperTypes="#//dynamicPage">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="EntityPages"/>
    </eAnnotations>
    <eOperations name="showInstanz" lowerBound="1" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexPages" eSuperTypes="#//dynamicPage">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="IndexPages"/>
    </eAnnotations>
    <eOperations name="showAll" lowerBound="1" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dymaicContent" eType="#//dynamicContent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdatePage" eSuperTypes="#//EntityPages">
    <eOperations name="editEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeletePage" eSuperTypes="#//EntityPages">
    <eOperations name="deleteEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreatePage" eSuperTypes="#//EntityPages">
    <eOperations name="createEntity" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="dynamicContent" instanceTypeName="dynamicContent"/>
</ecore:EPackage>
