<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="swml_metamodell"
    nsURI="http://swml_metamodell/1.0" nsPrefix="swml_metamodell">
  <eClassifiers xsi:type="ecore:EClass" name="ContentModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//ContentModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Enumerations" upperBound="-1"
        eType="#//Enumeration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="References" upperBound="-1"
        eType="#//Reference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataTyp" lowerBound="1"
        eType="#//DataTyp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTyp" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//DataTyp"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//DataTyp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//DataTyp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//DataTyp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Email" eSuperTypes="#//DataTyp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiteral" upperBound="-1"
        eType="#//Literals" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//DataTyp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RefTo" lowerBound="1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Opposite" eType="#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Entities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SuperClass" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literals"/>
</ecore:EPackage>
